# -*- coding: utf-8 -*-
"""Mario Party.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBXYI9850JuZKHQ_HpRXmwsB_65J8f0a
"""

# Mario Party Simple Dice Rolling Game

import random

# Function to simulate a dice roll
def roll_dice():
    return random.randint(1, 6)

# Function to simulate a player's turn
def player_turn(player_name):
    print(f"\n{player_name}'s Turn:")
    input("Press Enter to roll the dice...")
    roll = roll_dice()
    print(f"{player_name} rolled a {roll}")
    return roll

# Function to determine the winner
def determine_winner(player_scores):
    max_score = max(player_scores, key=player_scores.get)
    print(f"\nThe winner is {max_score} with a score of {player_scores[max_score]}!")
    return max_score

# Main game loop
def mario_party_game(player_names, rounds=5):
    player_scores = {name: 0 for name in player_names}

    for round_number in range(1, rounds + 1):
        print(f"\n--- Round {round_number} ---")
        for player in player_names:
            roll = player_turn(player)
            player_scores[player] += roll

    determine_winner(player_scores)

# List of players
players = ["Mario", "Luigi", "Peach", "Yoshi"]

# Start the game
mario_party_game(players)